eventFinderApp/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required
from django.conf.urls import url
from . import views

app_name = 'eventFinderApp'

urlpatterns = [
    # event-finder/
    path('', views.IndexView.as_view(), name='index'),
    # event-finder/1
    path('<int:pk>/', views.EventView.as_view(), name='event'),
    path('event_submit/', views.CreateEventView.as_view(), name='event_submit'),
    path('event_edit/<int:pk>/', views.EditEventView.as_view(), name='event_edit'),
    path('event_filter', views.FilterView.as_view(), name='event_filter'),
    ]

eventFinderProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog
from rest_framework import routers
from rest_framework.authtoken import views
from eventFinderApp import viewsets as EventViewsets
from users import viewsets as UserViewsets
import users

router = routers.DefaultRouter()
router.register(r'events', EventViewsets.EventViewSet)
router.register(r'users', UserViewsets.CustomUserViewSet)

urlpatterns = [
    path('event-finder/', include('eventFinderApp.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls') ,name='users'),
    path('api/', include(router.urls)),
    path(r'api-auth-token/', views.obtain_auth_token),
    path('jsi18n', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.LoginView.as_view, name = 'login'),
    path('logout/', views.LogoutView.as_view, name = 'logout'),
    path('<int:pk>/', views.UserDetailView.as_view(), name='account'),
    path('<int:pk>/edit_profile', views.EditUserDetailView.as_view(), name='edit_account')
]

eventFinderApp/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from users.models import CustomUser

class Event(models.Model):
    host = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, null = "True")
    title = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    venue = models.CharField(max_length=200, null="True")
    description = models.CharField(max_length=500, default="")
    start_time = models.DateTimeField('start time and date')
    end_time = models.DateTimeField('end time and date')
    categories = models.ManyToManyField('Category')

    def get_absolute_url(self):
        return reverse("eventFinderApp:event", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Permission, Group

class CustomUser(AbstractUser):
  first_name = models.CharField(max_length=50, default='')
  last_name = models.CharField(max_length=50, default='')
  def __str__(self):
    return self.username

eventFinderApp/forms.py
from django import forms
from django.forms import ModelForm, DateTimeInput
from django.contrib.admin import widgets

from .models import Event

class NewEventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = (
        'title', 
        'location', 
        'venue',  
        'start_time',
        'end_time',
        'description', 
        'categories',)
        widgets = {
            'start_time': widgets.AdminSplitDateTime,
            'end_time': widgets.AdminSplitDateTime,
        }

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
  class Meta(UserCreationForm):
      model = CustomUser
      fields = (
        'username', 
        'email',
        'first_name',
        'last_name',
        )

class CustomUserChangeForm(UserChangeForm):
  class Meta:
      model = CustomUser
      fields = (
        'username', 
        'email',
        'first_name',
        'last_name',
        )

eventFinderApp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import CreateView, UpdateView, DetailView, ListView

from .models import Event
from .forms import NewEventForm
from .filters import EventFilter


class IndexView(ListView):
    template_name = 'eventFinderApp/index.html'
    context_object_name = 'events_list'

    def get_queryset(self):
        '''Return the events.'''
        return Event.objects.all()

class EventView(DetailView):
    model = Event
    template_name = 'eventFinderApp/event.html'


class CreateEventView(LoginRequiredMixin, CreateView):
    template_name = 'eventFinderApp/event_submit.html'
    form_class = NewEventForm
    login_url = '/users/login/'

    def form_valid(self, form):
        form.instance.host = self.request.user
        print(form.cleaned_data)
        return super().form_valid(form)

class EditEventView(LoginRequiredMixin, UpdateView):
    template_name = 'eventFinderApp/event_edit.html'
    form_class = NewEventForm

    def get_object(self):
        event_id = self.kwargs.get('pk')
        return get_object_or_404(Event, pk=event_id, host=self.request.user)


class FilterView(ListView):
    template_name = 'eventFinderApp/event_filter.html'
    context_object_name = 'events_list'

    def get_queryset(self):
        '''Return the events.'''
        return Event.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = EventFilter(self.request.GET, queryset=self.get_queryset())
        return context

users/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CustomUserCreationForm, CustomUserChangeForm
from .models import CustomUser
from eventFinderApp.models import Event

class Register(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/register.html'

class Login(LoginView):
    template_name = 'registration/login.html'

class Logout(LogoutView):
    pass

class UserDetailView(DetailView):
    model = CustomUser
    template_name = 'account.html'

class EditUserDetailView(LoginRequiredMixin, UpdateView):
    template_name = 'edit_account.html'
    form_class = CustomUserChangeForm

    def get_success_url(self):
        user_id = self.kwargs['pk']
        return reverse_lazy('users:account', kwargs={'pk': user_id})

    def get_object(self):
        user_id = self.kwargs.get('pk')
        return get_object_or_404(CustomUser, pk=user_id)
    
        

eventFinderApp/templates/eventFinderApp/detailsBox.html
<div class="details-box">
    <a href="{% url 'eventFinderApp:event' event.id %}">
        <p>{{ event.title }}</p>
        <p>{{ event.start_time }}</p>
        {% for category in event.categories.all %}
        <p>{{ category.name }}</p>
        {% endfor %}
    </a>
</div>

eventFinderApp/templates/eventFinderApp/event.html
{% extends "base.html" %}

{% block content %}

<h2>{{ event.title }}</h2>

<p>{{ event.location }}</p>
<p>Starts at: {{ event.start_time }}</p>
<p>Ends at: {{ event.end_time }}</p>
<p>Venue: {{ event.venue }}</p>
<p>Host: {{ event.host.username }}</p>
<p>Categories: {% for category in event.categories.all %}
    <P>{{ category.name }} </P>
    {% endfor %}
</p>

{% if user.username == event.host.username %}
    <p><a href="{% url 'eventFinderApp:event_edit' event.id %}">Edit Event</a></p>
{% endif %}
{% endblock %}

eventFinderApp/templates/eventFinderApp/event_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>Edit Event</h2>
    <form method="POST" class="NewEventForm">
        {{ form.media }}
        {% csrf_token %}
        {{ form.title | as_crispy_field }}
        {{ form.venue | as_crispy_field}}
        {{ form.location | as_crispy_field }}
        {{ form.start_time | as_crispy_field }}
        {{ form.end_time| as_crispy_field }}
        {{ form.categories | as_crispy_field }}
        <button type="submit" value="Update" class="save btn btn-default">Save</button>
    </form>

{% endblock %}

eventFinderApp/templates/eventFinderApp/event_filter.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  
  <form method="GET">
    {{ form.media }}
    {{ filter.form|crispy }}
    <button type="submit">Search for Event</button>
  </form>

  <ul>
  {% for event in filter.qs %}
    <li><a href="{% url 'eventFinderApp:event' event.pk %}">{{ event.title }}</a></li>
  {% endfor %}
  </ul>

{% endblock %}

eventFinderApp/templates/eventFinderApp/event_submit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" class="NewEventForm">
        {{ form.media }}
        {% csrf_token %}
        {{ form.title | as_crispy_field }}
        {{ form.venue | as_crispy_field}}
        {{ form.location | as_crispy_field }}
        {{ form.description | as_crispy_field }}
        {{ form.start_time | as_crispy_field }}
        {{ form.end_time| as_crispy_field }}
        {{ form.categories | as_crispy_field }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

{% endblock %}

eventFinderApp/templates/eventFinderApp/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <div id="index-container" class="row">
        <div class="col-6">
            {% if events_list %}
                {% for event in events_list %}
                    {% include "./detailsBox.html" with event=event %}
                {% endfor %}
            {% else %}
                <p>No events are available.</p>
            {% endif %}
        </div>
        <div class="col-6">
            <div id="right-side-row" class="row">
                <div id="new-event-col" class="col right-side-col">
                    <a href="{% url 'eventFinderApp:event_submit' %}"><button id="new-event">CREATE NEW EVENT</button></a>
                </div>
                <div id="featured-col" class="col right-side-col">
                    <h2>featured events and reviews coming soon</h2>
                </div>
                <div id="frugal-col" class="col right-side-col">
                    <h2>frugal blog coming soon</h2>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

eventFinderApp/templates/eventFinderApp/name.html
<form action="/your-name/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Event Finder</title>
        <meta name="description" content="">
        <meta name="author" content="Sarah Levins">

        <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
        <script type="text/javascript" src="{% static '/admin/js/core.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static '/admin/css/widgets.css' %}">
        <style>
            .calendar>table>caption{caption-side:unset}
        </style><!--caption fix for bootstrap4-->

        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Bangers|Cinzel|Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'eventFinderApp/style.css' %}">

     

    </head>

    <body>
        <header>
            <div>
                <h1>You're Not Too Poor.</h1>
                <h2>No more excuses. Go out.</h2>
            </div>
            {% include './nav.html' %}

        </header>

        {% block content %}{% endblock %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

templates/nav.html
{% load static %}

<nav class = "navbar bg-light">
        <div id="navbar-wrapper">
        <div>
            <ul class="nav">
                <li class="nav-item">
                    <a href="{% url 'eventFinderApp:index' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'eventFinderApp:event_filter' %}">Search for Event</a>
                </li>
            </ul>
        </div>
        <div>
            {% if user.is_authenticated %}
            
            <div class="nav-item dropdown">
                <button class="btn dropdown-toggle" type="button" id="MyAccountDropDown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Hi {{ user.username }}
                </button>
                <div class="dropdown-menu" aria-labelledby="MyAccountDropDown">
                    <a class="dropdown-item" href="{% url 'users:account' user.pk %}">My Account</a>
                    <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                </div>
            </div>
    
            {% else %}
            <ul class="nav">
                <li class="nav-item">
                        <a href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                        <a href="{% url 'users:register' %}">Register</a>
                </li>
            </ul>
            {% endif %}
        </div>
        </div>
    </nav>

users/templates/account.html
{% extends "base.html" %}

{% block content %}

<h2>{{ user.username }}</h2>
<p>{{ user.email }}</p>

<h3>Events you are hosting:</h3>

<ul>
    {% for event in user.event_set.all %}
        <li>
            <a href="{% url 'eventFinderApp:event' event.pk %}">{{ event.title }}</a>
        </li>
    {% endfor %}
</ul>

{% endblock %}

users/templates/edit_account.html
{% extends "base.html" %}
{% load crispy_forms_tags %}



{% block content %}

    <h2>Update Profile</h2>

    <form method="POST" class="CustomUserChangeForm">
            {% csrf_token %}
            {{ form.username | as_crispy_field }}
            {{ form.email | as_crispy_field}}
            <button type="submit" value="Update" class="save btn btn-default">Save</button>
        </form>

{% endblock %}